name: "dimenet++"

model:
  emb_size: 128
  out_emb_size: 256
  int_emb_size: 64
  basis_emb_size: 8
  num_blocks: 4
  num_spherical: 7
  num_radial: 6
  envelope_exponent: 5
  cutoff: 5.0
  extensive: True
  num_before_skip: 1
  num_after_skip: 2
  num_dense_output: 3
  # ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv']
  targets: ['lumo']

train:
  lr: 0.001
  weight_decay: 0.0001
  ema_decay: 0.999
  batch_size: 100
  epochs: 800
  early_stopping: 20
  num_workers: 18
  gpu: 3
  interval: 50