name: "dimenet"
logname: "Joint2"
with_dyn: False
clean: True

model:
  emb_size: 128
  num_blocks: 6
  num_bilinear: 8
  num_spherical: 7
  num_radial: 6
  envelope_exponent: 5
  cutoff: 4.0
  num_before_skip: 1
  num_after_skip: 2
  num_dense_output: 3
  # ['mu', 'alpha', 'homo', 'lumo', 'gap', 'r2', 'zpve', 'U0', 'U', 'H', 'G', 'Cv']
  targets: ['Energy']

train:
  num_train: 2091 #1807,1569, 2410, 2092
  num_valid: 261 #602,523, 301, 261
  split_ratio: 0.6
  data_seed: 41
  lr: 0.001
  weight_decay: 0.0001
  ema_decay: 0
  batch_size: 5
  epochs: 160
  early_stopping: 20
  num_workers: 12
  gpu: 0
  interval: 10
  step_size: 25
  gamma: 0.3
  alpha: 10.0

pretrain:
  flag: False
  path: 'pretrained/converted/'